# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170118_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
