# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20171224_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
