# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180124_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='SMS_activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
