# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180129_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='SMS_activation_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_authenticated',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number_hash',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=False, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
