# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_sms_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
