# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_user_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
